//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1_Вариант3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Persons
    {
        public int Booking_id { get; set; }
        public int Person_id { get; set; }
        public short Ticket_count { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual Persons Persons { get; set; }
    }
}
