//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1_Вариант3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loginings
    {
        public int id { get; set; }
        public int User_id { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Login_time { get; set; }
        public Nullable<System.TimeSpan> Logout_time { get; set; }
        public Nullable<int> Time_spent_on { get; set; }
        public string GetShortDate
        {
            get
            {
                return Date.ToShortDateString();
            }
        }

        public string GetLoginTime
        {
            get
            {
                return GetCorrectTime(Login_time);
            }
        }

        public string GetLogoutTime
        {
            get
            {
                if (Logout_time != null)
                {
                    return GetCorrectTime((TimeSpan)Logout_time);
                }
                else
                    return "**";
            }
        }

        public string Time_spent
        {
            get
            {
                if (Time_spent_on != null)
                {
                    TimeSpan WhatIsTime = TimeSpan.FromSeconds((int)Time_spent_on);
                    return GetCorrectTime(WhatIsTime);
                }
                else
                    return "**";
            }
        }

        private string GetCorrectTime(TimeSpan time)
        {
            string correctTime = $"{time.Seconds}";
            if (time.Minutes > 0)
                correctTime = $"{time.ToString("%m':'ss")}";
            if (time.Hours > 0)
                correctTime = $"{time.ToString("%h':'mm':'ss")}";
            return correctTime;
        }
        public string Error_reason { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
