//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1_Вариант3.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Session1_3 : DbContext
    {
        private static Session1_3 _context;
        public Session1_3()
            : base("name=Session1_3")
        {
        }
        public static Session1_3 GetContext()
        {
            if (_context == null) 
                _context = new Session1_3();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aircraft> Aircraft { get; set; }
        public virtual DbSet<Billings> Billings { get; set; }
        public virtual DbSet<Booking_Persons> Booking_Persons { get; set; }
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Flight_Scheludes> Flight_Scheludes { get; set; }
        public virtual DbSet<Loginings> Loginings { get; set; }
        public virtual DbSet<Offices> Offices { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
