//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1_Вариант3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Loginings = new HashSet<Loginings>();
        }
    
        public int id { get; set; }
        public string Role { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Title { get; set; }
        public System.DateTime Birthdate { get; set; }
        public Nullable<int> Office_id { get; set; }
        public int Age
        {
            get { return DateTime.Now.Year - Birthdate.Year; }
        }
        public string OfficeName
        {
            get
            {
                if (Offices != null)
                    return Offices.Name;
                return "**";
            }
        }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loginings> Loginings { get; set; }
        public virtual Offices Offices { get; set; }
    }
}
